### ISSUE TITLE
Hello, the saved model has two parts, model teacher and model student. Which part do I use for verification?

### ISSUE THREAD

**Issue by mary-0830** [facebookresearch/unbiased-teacher-v2#2]

**Comment by ycliu93** [comment]
Usually the Teacher model performs higher results compared with the Student model. We used the Teacher model to report our results. Unbiased Teacher v1 also uses the Teacher model. 

Also, the Teacher model might get zeros mAP during the burn-in stage, since it is randomly initialized without gradient updates or EMA updates from the Student.
